export const SlashTipAbi = [
	{
		type: "constructor",
		inputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "DEFAULT_ADMIN_ROLE",
		inputs: [],
		outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "TIP_MANAGER",
		inputs: [],
		outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "addAllowanceForAllUsers",
		inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "allowanceOf",
		inputs: [{ name: "_userId", type: "string", internalType: "string" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "initialize",
		inputs: [
			{ name: "_admin", type: "address", internalType: "address" },
			{ name: "_userRegistry", type: "address", internalType: "address" },
			{ name: "_tipAction", type: "address", internalType: "address" },
			{ name: "_orgId", type: "string", internalType: "string" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "orgId",
		inputs: [],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "setAllowanceForAllUsers",
		inputs: [{ name: "_amount", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setTipAction",
		inputs: [{ name: "_tipAction", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "setUserRegistry",
		inputs: [{ name: "_userRegistry", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "tip",
		inputs: [
			{ name: "_fromId", type: "string", internalType: "string" },
			{ name: "_toId", type: "string", internalType: "string" },
			{ name: "_amount", type: "uint256", internalType: "uint256" },
			{ name: "_data", type: "string", internalType: "string" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "tipAction",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contract ITipAction" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "userRegistry",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contract UserRegistry" }],
		stateMutability: "view",
	},
	{
		type: "event",
		name: "Tipped",
		inputs: [
			{ name: "fromId", type: "string", indexed: true, internalType: "string" },
			{ name: "toId", type: "string", indexed: true, internalType: "string" },
			{ name: "fromAddress", type: "address", indexed: true, internalType: "address" },
			{ name: "toAddress", type: "address", indexed: false, internalType: "address" },
			{ name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
			{ name: "data", type: "string", indexed: false, internalType: "string" },
			{ name: "actionContract", type: "address", indexed: false, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "TipActionUpdated",
		inputs: [
			{ name: "oldAction", type: "address", indexed: true, internalType: "address" },
			{ name: "newAction", type: "address", indexed: true, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "UserRegistryUpdated",
		inputs: [
			{ name: "oldRegistry", type: "address", indexed: true, internalType: "address" },
			{ name: "newRegistry", type: "address", indexed: true, internalType: "address" },
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Initialized",
		inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
		anonymous: false,
	},
	{
		type: "error",
		name: "InsufficientAllowance",
		inputs: [
			{ name: "userId", type: "string", internalType: "string" },
			{ name: "allowance", type: "uint256", internalType: "uint256" },
			{ name: "required", type: "uint256", internalType: "uint256" },
		],
	},
	{
		type: "error",
		name: "UserNotFound",
		inputs: [{ name: "userId", type: "string", internalType: "string" }],
	},
] as const;

export default SlashTipAbi;
